services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD_FILE: ${MYSQL_ROOT_PASSWORD_FILE}
      MYSQL_PASSWORD_FILE: ${MYSQL_PASSWORD_FILE}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    secrets:
      - db_root_password
      - db_password
    healthcheck:
      test: ["CMD-SHELL", 'mariadb-admin ping -h 127.0.0.1 -uroot -p"$$(cat /run/secrets/db_root_password)" || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_URL: https://${DOMAIN_NAME}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WORDPRESS_USER_PASSWORD: ${WORDPRESS_USER_PASSWORD}
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_healthy
      adminer:
        condition: service_healthy
      static-site:
        condition: service_healthy
      grafana:
        condition: service_healthy
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      SSL_COUNTRY: ${SSL_COUNTRY}
      SSL_STATE: ${SSL_STATE}
      SSL_CITY: ${SSL_CITY}
      SSL_ORGANIZATION: ${SSL_ORGANIZATION}
      SSL_OU: ${SSL_OU}
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception_network
    ports:
      - "443:443"
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 443 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  ftp:
    build: ./requirements/bonus/ftp/
    container_name: ftp
    depends_on:
      wordpress:
        condition: service_healthy
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASSWORD: ${FTP_PASSWORD}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 21 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  redis:
    build: ./requirements/bonus/redis/
    container_name: redis
    volumes:
      - redis_data:/var/lib/redis
    networks:
      - inception_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  adminer:
    build: ./requirements/bonus/adminer/
    container_name: adminer
    networks:
      - inception_network
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  static-site:
    build: ./requirements/bonus/static-site/
    container_name: static-site
    networks:
      - inception_network
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  grafana:
    build: ./requirements/bonus/grafana/
    container_name: grafana
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_SECURITY_SECRET_KEY: ${GRAFANA_SECRET_KEY}
      GF_SERVER_DOMAIN: ${DOMAIN_NAME}
      GF_SERVER_ROOT_URL: https://${DOMAIN_NAME}/grafana/
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      GF_MARIADB_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - inception_network
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

networks:
  inception_network:
    driver: bridge
    name: inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wordpress
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/redis
  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/grafana

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
