ALTER USER 'root'@'localhost' IDENTIFIED BY 'REPLACE_ROOT_PASSWORD';
DELETE FROM mysql.user WHERE User='';
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
DROP DATABASE IF EXISTS test;
DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';

CREATE DATABASE IF NOT EXISTS REPLACE_DATABASE_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'REPLACE_USERNAME'@'localhost' IDENTIFIED BY 'REPLACE_USER_PASSWORD';
CREATE USER 'REPLACE_USERNAME'@'%' IDENTIFIED BY 'REPLACE_USER_PASSWORD';

GRANT ALL PRIVILEGES ON REPLACE_DATABASE_NAME.* TO 'REPLACE_USERNAME'@'localhost';
GRANT ALL PRIVILEGES ON REPLACE_DATABASE_NAME.* TO 'REPLACE_USERNAME'@'%';
FLUSH PRIVILEGES;
