apiVersion: 1

datasources:
  - name: MariaDB
    type: mysql
    access: proxy
    url: mariadb:3306
    database: ${MYSQL_DATABASE}
    user: ${MYSQL_USER}
    secureJsonData:
      password: ${GF_MARIADB_PASSWORD}
    jsonData:
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
    editable: true
